'use strict';
/**
 * Returns a random Person Object with firstname, surname and country
 * @return {object}
 */

function randomPerson() {
    return people[Math.floor(Math.random() * people.length)];
}

module.exports = {
    generate: randomPerson,
    amount: function amount() {
        return people.length;
    }
};

var people = [
//German
{firstname: "Alexander", surname: "Müller", country:"DE"},
{firstname: "Astrid", surname: "Schulz", country:"DE"},
{firstname: "Amelie",surname: "Schmidt", country:"DE"},
{firstname: "Anna", surname: "Schneider", country:"DE"},
{firstname: "Anton", surname: "Fischer", country:"DE"},
{firstname: "Ben", surname: "Weber", country:"DE"},
{firstname: "Carl", surname: "Mayer", country:"DE"},
{firstname: "Charlotte", surname: "Wagner", country:"DE"},
{firstname: "Clara", surname: "Becker", country:"DE"},
{firstname: "David", surname: "Hoffmann", country:"DE"},
{firstname: "Elias", surname: "Schäfer", country:"DE"},
{firstname: "Elisa", surname: "Koch", country:"DE"},
{firstname: "Ella", surname: "Bauer", country:"DE"},
{firstname: "Emil", surname: "Richter", country:"DE"},
{firstname: "Emilia",surname: "Klein", country:"DE"},
{firstname: "Emily", surname: "Wolf", country:"DE"},
{firstname: "Emma", surname: "Schröder", country:"DE"},
{firstname: "Erik", surname: "Neumann", country:"DE"},
{firstname: "Fabian",surname: "Schwarz", country:"DE"},
{firstname: "Felix", surname: "Zimmermann", country:"DE"},
{firstname: "Finn", surname: "Braun", country:"DE"},
{firstname: "Frieda",surname: "Krüger", country:"DE"},
{firstname: "Greta", surname: "Hartmann", country:"DE"},
{firstname: "Hannah",surname: "Lange", country:"DE"},
{firstname: "Hannes",surname: "Schmitt", country:"DE"},
{firstname: "Helena",surname: "Werner", country:"DE"},
{firstname: "Henry", surname: "Schmitz", country:"DE"},
{firstname: "Ida", surname: "Krause", country:"DE"},
{firstname: "Isabell",  surname: "Meier", country:"DE"},
{firstname: "Isabella", surname: "Lehmann", country:"DE"},
{firstname: "Jakob", surname: "Schmid", country:"DE"},
{firstname: "Jan", surname: "Schulze", country:"DE"},
{firstname: "Jannik",surname: "Maier", country:"DE"},
{firstname: "Johanna", surname: "Köhler", country:"DE"},
{firstname: "Johannes", surname: "Herrmann", country:"DE"},
{firstname: "Jona", surname: "König", country:"DE"},
{firstname: "Jonas", surname: "Walter", country:"DE"},
{firstname: "Jonathan", surname: "Mayer", country:"DE"},
{firstname: "Josephine", surname: "Huber", country:"DE"},
{firstname: "Julia", surname: "Kaiser", country:"DE"},
{firstname: "Julian",surname: "Fuchs", country:"DE"},
{firstname: "Lara", surname: "Peters", country:"DE"},
{firstname: "Laura", surname: "Lang", country:"DE"},
{firstname: "Lea", surname: "Scholz", country:"DE"},
{firstname: "Lena", surname: "Möller", country:"DE"},
{firstname: "Leni", surname: "Weiß", country:"DE"},
{firstname: "Lennard", surname: "Jung", country:"DE"},
{firstname: "Leo", surname: "Hahn", country:"DE"},
{firstname: "Leon", surname: "Schubert", country:"DE"},
{firstname: "Leonie",surname: "Vogel", country:"DE"},
{firstname: "Lia", surname: "Friedrich", country:"DE"},
{firstname: "Liam", surname: "Keller", country:"DE"},
{firstname: "Lilly", surname: "Günther", country:"DE"},
{firstname: "Lina", surname: "Frank", country:"DE"},
{firstname: "Linus", surname: "Berger", country:"DE"},
{firstname: "Lisa", surname: "Winkler", country:"DE"},
{firstname: "Lotta", surname: "Roth", country:"DE"},
{firstname: "Luca", surname: "Beck", country:"DE"},
{firstname: "Luis", surname: "Lorenz", country:"DE"},
{firstname: "Luisa", surname: "Baumann", country:"DE"},
{firstname: "Lukas", surname: "Franke", country:"DE"},
{firstname: "Maja", surname: "Albrecht", country:"DE"},
{firstname: "Mara", surname: "Schuster", country:"DE"},
{firstname: "Marie", surname: "Simon", country:"DE"},
{firstname: "Marlene", surname: "Ludwig", country:"DE"},
{firstname: "Mathilda", surname: "Böhm", country:"DE"},
{firstname: "Mats", surname: "Winter", country:"DE"},
{firstname: "Matteo",surname: "Kraus", country:"DE"},
{firstname: "Max", surname: "Martin", country:"DE"},
{firstname: "Maximilian", surname: "Schumacher", country:"DE"},
{firstname: "Melina",surname: "Krämer", country:"DE"},
{firstname: "Mia", surname: "Vogt", country:"DE"},
{firstname: "Mika", surname: "Stein", country:"DE"},
{firstname: "Mila", surname: "Jäger", country:"DE"},
{firstname: "Milan", surname: "Otto", country:"DE"},
{firstname: "Mira", surname: "Sommer", country:"DE"},
{firstname: "Moritz",surname: "Groß", country:"DE"},
{firstname: "Nele", surname: "Seidel", country:"DE"},
{firstname: "Nico", surname: "Heinrich", country:"DE"},
{firstname: "Niklas",surname: "Brandt", country:"DE"},
{firstname: "Noah", surname: "Haas", country:"DE"},
{firstname: "Nora", surname: "Schreiber", country:"DE"},
{firstname: "Oskar", surname: "Graf", country:"DE"},
{firstname: "Paul", surname: "Schulte", country:"DE"},
{firstname: "Paula", surname: "Dietrich", country:"DE"},
{firstname: "Philipp",  surname: "Ziegler", country:"DE"},
{firstname: "Pia", surname: "Kuhn", country:"DE"},
{firstname: "Rafael",surname: "Kühn", country:"DE"},
{firstname: "Samuel",surname: "Pohl", country:"DE"},
{firstname: "Sarah", surname: "Engel", country:"DE"},
{firstname: "Simon", surname: "Horn", country:"DE"},
{firstname: "Sofia", surname: "Busch", country:"DE"},
{firstname: "Sophie",surname: "Bergmann", country:"DE"},
{firstname: "Theo", surname: "Thomas", country:"DE"},
{firstname: "Till", surname: "Voigt", country:"DE"},
{firstname: "Tim", surname: "Sauer", country:"DE"},
{firstname: "Tom", surname: "Arnold", country:"DE"},
{firstname: "Victoria", surname: "Wolff", country:"DE"},

//US
{firstname: "Aaron", surname: "Smith", country: "US"},
{firstname: "Abby", surname: "Griffin", country: "US"},
{firstname: "Adam", surname: "Russell", country: "US"},
{firstname: "Gale", surname: "Alexander", country: "US"},
{firstname: "Alexis", surname: "Bryant", country: "US"},
{firstname: "Alyssa", surname: "Gonzales", country: "US"},
{firstname: "Amanda", surname: "Foster", country: "US"},
{firstname: "Amber", surname: "Simmons", country: "US"},
{firstname: "Andre", surname: "Butler", country: "US"},
{firstname: "Anna", surname: "Washington", country: "US"},
{firstname: "Anthony", surname: "Flores", country: "US"},
{firstname: "Ashley", surname: "Hughes", country: "US"},
{firstname: "Austin", surname: "Patterson", country: "US"},
{firstname: "Ben", surname: "Long", country: "US"},
{firstname: "Brandon", surname: "Powell", country: "US"},
{firstname: "Brian", surname: "Perry", country: "US"},
{firstname: "Brianna", surname: "Jenkins", country: "US"},
{firstname: "Brittany", surname: "Coleman", country: "US"},
{firstname: "Brooke", surname: "Henderson", country: "US"},
{firstname: "Caleb", surname: "Ross", country: "US"},
{firstname: "Cameron", surname: "Barnes", country: "US"},
{firstname: "Chloe", surname: "Wood", country: "US"},
{firstname: "Chris", surname: "Bennett", country: "US"},
{firstname: "Christian", surname: "Price", country: "US"},
{firstname: "Christopher", surname: "Sanders", country: "US"},
{firstname: "Courtney", surname: "Kelly", country: "US"},
{firstname: "Danie", surname: "Brooks", country: "US"},
{firstname: "Danielle", surname: "Watson", country: "US"},
{firstname: "David", surname: "James", country: "US"},
{firstname: "Dylan", surname: "Ramirez", country: "US"},
{firstname: "Elizabeth", surname: "Gray", country: "US"},
{firstname: "Emily", surname: "Peterson", country: "US"},
{firstname: "Emma", surname: "Torres", country: "US"},
{firstname: "Eric", surname: "Ward", country: "US"},
{firstname: "Erin", surname: "Howard", country: "US"},
{firstname: "Ethan", surname: "Cox", country: "US"},
{firstname: "Grace", surname: "Richardson", country: "US"},
{firstname: "Haley", surname: "Cooper", country: "US"},
{firstname: "Hannah", surname: "Rivera", country: "US"},
{firstname: "Hunter", surname: "Bailey", country: "US"},
{firstname: "Jack", surname: "Murphy", country: "US"},
{firstname: "Jaco", surname: "Bell", country: "US"},
{firstname: "Jake", surname: "Morgan", country: "US"},
{firstname: "james", surname: "Cook", country: "US"},
{firstname: "Jasmine", surname: "Reed", country: "US"},
{firstname: "Jason", surname: "Rogers", country: "US"},
{firstname: "Jennifer", surname: "Morris", country: "US"},
{firstname: "Jessica", surname: "Sanchez", country: "US"},
{firstname: "Joe", surname: "Stewart", country: "US"},
{firstname: "Joh", surname: "Collins", country: "US"},
{firstname: "Jonathan", surname: "Edwards", country: "US"},
{firstname: "Jordan", surname: "Evans", country: "US"},
{firstname: "Jordan", surname: "Parker", country: "US"},
{firstname: "Joseph", surname: "Campbell", country: "US"},
{firstname: "Josh", surname: "Phillips", country: "US"},
{firstname: "Joshua", surname: "Turner", country: "US"},
{firstname: "Julia", surname: "Roberts", country: "US"},
{firstname: "Justin", surname: "Perez", country: "US"},
{firstname: "Katie", surname: "Mitchell", country: "US"},
{firstname: "Kayla", surname: "Carter", country: "US"},
{firstname: "Kevin", surname: "Nelson", country: "US"},
{firstname: "Kyle", surname: "Gonzalez", country: "US"},
{firstname: "Lauren", surname: "Baker", country: "US"},
{firstname: "Lily", surname: "Adams", country: "US"},
{firstname: "Logan", surname: "Green", country: "US"},
{firstname: "Luke", surname: "Scott", country: "US"},
{firstname: "Maddie", surname: "Hill", country: "US"},
{firstname: "Madison", surname: "Lopez", country: "US"},
{firstname: "Mary", surname: "Wright", country: "US"},
{firstname: "Matt", surname: "King", country: "US"},
{firstname: "Matthe", surname: "Hernandez", country: "US"},
{firstname: "Megan", surname: "Young", country: "US"},
{firstname: "Michae", surname: "Allen", country: "US"},
{firstname: "Michelle", surname: "Hall", country: "US"},
{firstname: "Morgan", surname: "Walker", country: "US"},
{firstname: "Natalie", surname: "Lee", country: "US"},
{firstname: "Nathan", surname: "Lewis", country: "US"},
{firstname: "Nick", surname: "Rodriguez", country: "US"},
{firstname: "Nicole", surname: "Clark", country: "US"},
{firstname: "Noah", surname: "Robinson", country: "US"},
{firstname: "Olivia", surname: "Martinez", country: "US"},
{firstname: "Paige", surname: "Garcia", country: "US"},
{firstname: "Rachel", surname: "Thompson", country: "US"},
{firstname: "Rebecca", surname: "Martin", country: "US"},
{firstname: "Robert", surname: "Harris", country: "US"},
{firstname: "Ryan", surname: "White", country: "US"},
{firstname: "Sam", surname: "Jackson", country: "US"},
{firstname: "Samantha", surname: "Thomas", country: "US"},
{firstname: "Sara", surname: "Anderson", country: "US"},
{firstname: "Sarah", surname: "Taylor", country: "US"},
{firstname: "Savannah", surname: "Moore", country: "US"},
{firstname: "Shelby",surname: "Wilson", country: "US"},
{firstname: "Stephanie",surname: "Miller", country: "US"},
{firstname: "Sydney", surname: "Davis", country: "US"},
{firstname: "Taylor",surname: "Brown", country: "US"},
{firstname: "Thomas",surname: "Jones", country: "US"},
{firstname: "William",surname: "Williams", country: "US"},
{firstname: "Zach",surname: "Johnson", country: "US"},

//Japan
{firstname: "Ai", surname: "Sato", country: "JP"},
{firstname: "Aika", surname: "Suzuki", country: "JP"},
{firstname: "Airi", surname: "Takahashi", country: "JP"},
{firstname: "Akari", surname: "Tanaka", country: "JP"},
{firstname: "Aki", surname: "Watanabe", country: "JP"},
{firstname: "Aki", surname: "Ito", country: "JP"},
{firstname: "Anna", surname: "Yamamoto", country: "JP"},
{firstname: "Atsushi", surname: "Nakamura", country: "JP"},
{firstname: "Aya", surname: "Kobayashi", country: "JP"},
{firstname: "Ayaka", surname: "Kato", country: "JP"},
{firstname: "Ayano", surname: "Yoshida", country: "JP"},
{firstname: "Ayumi", surname: "Yamada", country: "JP"},
{firstname: "Brad", surname: "Sasaki", country: "JP"},
{firstname: "Chihiro", surname: "Yamaguchi", country: "JP"},
{firstname: "Daisuke", surname: "Saito", country: "JP"},
{firstname: "Eri", surname: "Matsumoto", country: "JP"},
{firstname: "Erika", surname: "Inoue", country: "JP"},
{firstname: "Evan", surname: "Kimura", country: "JP"},
{firstname: "Haruka", surname: "Hayashi", country: "JP"},
{firstname: "Haruna", surname: "Shimizu", country: "JP"},
{firstname: "Hayato", surname: "Yamazaki", country: "JP"},
{firstname: "Hikaru", surname: "Mori", country: "JP"},
{firstname: "Hiro", surname: "Abe", country: "JP"},
{firstname: "Hiroaki", surname: "Ikeda", country: "JP"},
{firstname: "Hiroki", surname: "Hashimoto", country: "JP"},
{firstname: "Issei", surname: "Yamashita", country: "JP"},
{firstname: "Jason", surname: "Ishikawa", country: "JP"},
{firstname: "Kaito", surname: "Nakajima", country: "JP"},
{firstname: "Kana", surname: "Maeda", country: "JP"},
{firstname: "Kanako", surname: "Fujita", country: "JP"},
{firstname: "Kaori", surname: "Ogawa", country: "JP"},
{firstname: "KaZU", surname: "Goto", country: "JP"},
{firstname: "kazuki", surname: "Okada", country: "JP"},
{firstname: "kazuma", surname: "Hasegawa", country: "JP"},
{firstname: "Kazuya", surname: "Murakami", country: "JP"},
{firstname: "Keita", surname: "Kondo", country: "JP"},
{firstname: "Ken", surname: "Ishii", country: "JP"},
{firstname: "Kenta", surname: "Saito", country: "JP"},
{firstname: "Ko", surname: "Sakamoto", country: "JP"},
{firstname: "Kouki", surname: "Endo", country: "JP"},
{firstname: "Mai", surname: "Aoki", country: "JP"},
{firstname: "Mao", surname: "Fujii", country: "JP"},
{firstname: "Mari", surname: "Nishimura", country: "JP"},
{firstname: "Marina", surname: "Fukuda", country: "JP"},
{firstname: "Masa", surname: "Ota", country: "JP"},
{firstname: "Masaki", surname: "Miura", country: "JP"},
{firstname: "Mayu", surname: "Fujiwara", country: "JP"},
{firstname: "Mei", surname: "Okamoto", country: "JP"},
{firstname: "Miho", surname: "Matsuda", country: "JP"},
{firstname: "Mika", surname: "Nakagawa", country: "JP"},
{firstname: "Miki", surname: "Nakano", country: "JP"},
{firstname: "Mina", surname: "Harada", country: "JP"},
{firstname: "Minami", surname: "Ono", country: "JP"},
{firstname: "Mio", surname: "Tamura", country: "JP"},
{firstname: "Misa", surname: "Takeuchi", country: "JP"},
{firstname: "Miyu", surname: "Kaneko", country: "JP"},
{firstname: "Moe", surname: "Wada", country: "JP"},
{firstname: "Nana", surname: "Nakayama", country: "JP"},
{firstname: "Nao", surname: "Ishida", country: "JP"},
{firstname: "Naoki", surname: "Ueda", country: "JP"},
{firstname: "Naoto", surname: "Morita", country: "JP"},
{firstname: "Naoya", surname: "Hara", country: "JP"},
{firstname: "Natsuki", surname: "Shibata", country: "JP"},
{firstname: "Natsumi", surname: "Sakai", country: "JP"},
{firstname: "Ren", surname: "Kudo", country: "JP"},
{firstname: "Rin", surname: "Yokoyama", country: "JP"},
{firstname: "Rina", surname: "Miyazaki", country: "JP"},
{firstname: "Risa", surname: "Miyamoto", country: "JP"},
{firstname: "Ryo", surname: "Uchida", country: "JP"},
{firstname: "Ryota", surname: "Takagi", country: "JP"},
{firstname: "Saki", surname: "Ando", country: "JP"},
{firstname: "Sakura", surname: "Taniguchi", country: "JP"},
{firstname: "Saya", surname: "Ohno", country: "JP"},
{firstname: "sayaka", surname: "Maruyama", country: "JP"},
{firstname: "Shiho", surname: "Imai", country: "JP"},
{firstname: "Shinji", surname: "Takada", country: "JP"},
{firstname: "Shiori", surname: "Fujimoto", country: "JP"},
{firstname: "Sho", surname: "Takeda", country: "JP"},
{firstname: "Shota", surname: "Murata", country: "JP"},
{firstname: "Shun", surname: "Ueno", country: "JP"},
{firstname: "Shuto", surname: "Sugiyama", country: "JP"},
{firstname: "Taichi", surname: "Masuda", country: "JP"},
{firstname: "Taiyo", surname: "Sugawara", country: "JP"},
{firstname: "Taka", surname: "Hirano", country: "JP"},
{firstname: "Takumi", surname: "Kojima", country: "JP"},
{firstname: "Takuya", surname: "Otsuka", country: "JP"},
{firstname: "Tatsuya", surname: "Chiba", country: "JP"},
{firstname: "Tohru", surname: "Kubo", country: "JP"},
{firstname: "Tom", surname: "Matsui", country: "JP"},
{firstname: "You", surname: "Iwasaki", country: "JP"},
{firstname: "Yu", surname: "Sakurai", country: "JP"},
{firstname: "Yui", surname: "Kinoshita", country: "JP"},
{firstname: "Yuka", surname: "Noguchi", country: "JP"},
{firstname: "Yuki", surname: "Matsuo", country: "JP"},
{firstname: "Yuki", surname: "Nomura", country: "JP"},
{firstname: "Yuma", surname: "Kikuchi", country: "JP"},
{firstname: "Yumi", surname: "Sano", country: "JP"},
{firstname: "Yuna", surname: "Onishi", country: "JP"},
];